<a href="branchform">Add New Branch</a></br>
<a href="viewbranch">View Branches</a></br>
<a href="accountantform">Add New Accountant</a></br>
<a href="viewaccountant">View Accountants</a></br>
<a href="studentform">Add New Student</a></br>
<a href="viewstudentlist">View Student List</a></br>
<a href="paymentform">Payment Form</a></br>
<a href="viewpaymentdetails">View Payment Details</a></br>
<a href="courseform">Add New Course</a></br>
<a href="viewcourse">View Course Details</a></br>
<a href="accountant">adminnnnnn func</a>
<a href="searchstudent">aountant funcccc</a>
<a href="login">Login</a></br>
<a href="register">Register</a> 
<a href="accountant">Admin Search</a>